name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag elibonanni/midterm_review/docker
    - name: Push the image to DockerHub
      run: docker login -u elibonanni -p ${{ secrets.DOCKER_TOKEN }} && docker push elibonanni/midterm_review
